server:
  port: 8082
  #  ssl:
  #    key-store: classpath:yiqikang.xyz.pfx
  #    key-store-password: wha42jmq4982m
  #    key-store-type: PKCS12
  #    key-alias: yiqikang.xyz
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://1.15.30.214:3306/free?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: abc123400197
#    hikari:
#      minimum-idle: 10
#      maximum-pool-size: 100
#      idle-timeout: 1200
#      pool-name: HikariPool-ls&zy
#      max-lifetime: 3000
#      connection-timeout: 1200

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  redis:
    database: 0
    host: 1.15.30.214
    port: 6379
    password: Lishuai0923
    timeout: 1000


mybatis-plus:
  global-config:
    db-config:
      #字段策略，默认非NULL判断
      field-strategy: not_null
  configuration:
    map-underscore-to-camel-case: true

mini-app:
  app-id: wxa065435a8843b4c7
  app-secret: 0be67b8bb9f51fd6b7ccf1eac3dac516


#日志路径
logback:
  dir: logs
  #文件名称
  filename:
    all: springboot-base-frame-all
    info: springboot-base-frame-info
    warn: springboot-base-frame-warn
    error: springboot-base-frame-error
  #文件的最大数量
  maxhistory: 10
  #文件的最大文件大小
  maxfilesize: 100MB
  #日志级别
  level: debug
  #日志字符编码
  charset: UTF-8
  #日志格式
  CONSOLE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} %boldYellow([%thread]) %highlight(%-5level) %boldGreen(%logger{50}) - %msg%n'
  FILE_LOG_PATTERN: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'